### ISSUE TITLE
Issue in prebuild

### ISSUE THREAD

**Issue by sevketaydogdu** [langtube/expo-config-plugin-ios-share-extension#17]
i installed config plugin and  added below codes in my app.json in plugins, but npx expo prebuild is giving error.

Can you help me what am i doing wrong? @timedtext 
```
[
        "expo-config-plugin-ios-share-extension",
        {
          "activationRules": {
            "NSExtensionActivationSupportsText": true,
            "NSExtensionActivationSupportsWebURLWithMaxCount": 1,
            "NSExtensionActivationSupportsWebPageWithMaxCount": 1,
            "NSExtensionActivationSupportsImageWithMaxCount": 1
          }
        }
      ],
      [
        "./plugins/withAndroidShareExtension/index",
        {
          "androidIntentFilters": ["text/*", "image/*"]
        }
      ]
```
----

```
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
    at correctForPath (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/xcode/lib/pbxProject.js:1682:38)
    at correctForResourcesPath (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/xcode/lib/pbxProject.js:1672:12)
    at pbxProject.addResourceFile (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/xcode/lib/pbxProject.js:258:9)
    at /Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-config-plugin-ios-share-extension/build/withShareExtensionXcodeTarget.js:37:20
    at async action (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-config-plugin-ios-share-extension/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:23)
    at async interceptingMod (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/expo-config-plugin-ios-share-extension/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/sevketaydogdu/Documents/GitHub/PoliticcaMobile/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
```
My Dependencies

```
 "@expo/metro-config": "^0.10.7",
    "@expo/vector-icons": "^13.0.0",
    "@flyerhq/react-native-link-preview": "^1.6.0",
    "@hookform/resolvers": "^3.2.0",
    "@likashefqet/react-native-image-zoom": "^2.1.1",
    "@microsoft/signalr": "^7.0.12",
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-firebase/analytics": "^18.7.1",
    "@react-native-firebase/app": "^18.7.1",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.0.2",
    "@reduxjs/toolkit": "^1.9.5",
    "@sentry/react-native": "5.5.0",
    "@shopify/flash-list": "1.4.3",
    "@tamagui/animations-react-native": "^1.39.6",
    "@tamagui/babel-plugin": "^1.39.6",
    "@tamagui/config": "^1.39.6",
    "@tamagui/font-inter": "^1.39.6",
    "@tamagui/theme-base": "^1.39.6",
    "axios": "^1.5.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "expo": "^49.0.6",
    "expo-application": "~5.3.0",
    "expo-build-properties": "~0.8.3",
    "expo-config-plugin-ios-share-extension": "^0.0.4",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.6",
    "expo-device": "~5.4.0",
    "expo-doctor": "^1.1.3",
    "expo-document-picker": "~11.5.4",
    "expo-file-system": "~15.4.4",
    "expo-font": "~11.4.0",
    "expo-haptics": "~12.4.0",
    "expo-image": "~1.3.2",
    "expo-image-picker": "~14.3.2",
    "expo-insights": "~0.2.0",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-localization": "~14.3.0",
    "expo-notifications": "~0.20.1",
    "expo-router": "^2.0.14",
    "expo-secure-store": "~12.3.1",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-store-review": "~6.4.0",
    "expo-system-ui": "~2.4.0",
    "expo-updates": "~0.18.11",
    "expo-web-browser": "~12.3.2",
    "fast-xml-parser": "^4.2.7",
    "humanize-duration": "^3.30.0",
    "i18n-js": "^4.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.45.4",
    "react-native": "0.72.3",
    "react-native-avoid-softinput": "^4.0.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-mmkv": "^2.10.2",
    "react-native-pager-view": "6.2.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-receive-sharing-intent": "^2.0.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-web": "~0.19.6",
    "react-native-xml2js": "^1.0.3",
    "react-redux": "^8.1.2",
    "redux-persist": "^6.0.0",
    "sentry-expo": "~7.0.0",
    "swr": "^2.2.0",
    "tamagui": "^1.39.6",
    "yup": "^1.2.0"
```

**Comment by timedtext** [comment]
Sorry for the late response. Have you seen[ this guide](https://github.com/timedtext/expo-config-plugin-ios-share-extension#package-version-incompatibility)?

**Comment by sevketaydogdu** [comment]
thank you for answering. i was missed that part of guide.

but after integrated that part also in share menu my app is appearing. i want to use also "react-native-share-intent" but when i try to use hook  [https://github.com/achorein/expo-share-intent-demo in this repo](https://github.com/achorein/expo-share-intent-demo/blob/main/hooks/useShareIntent.js) there is no recieving any data. only expo-linking url getting data with useUrl like in your read me file.

What should i do  i dont know

**Comment by timedtext** [comment]
You can open an issue in [https://github.com/achorein/expo-share-intent-demo](https://github.com/achorein/expo-share-intent-demo/blob/main/hooks/useShareIntent.js?rgh-link-date=2023-12-22T10%3A12%3A12Z) to ask your question.

**Comment by sevketaydogdu** [comment]
thank you for your time @timedtext
