### ISSUE TITLE
 Cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by joshmohrer** [langtube/expo-config-plugin-ios-share-extension#19]
I was wondering if anyone has seen this error before while building a project with expo-config-plugin-ios-share-extension 
Any ideas? This is with Expo 50.

✔ Cleared android, ios code
✔ Created native directories
✔ Updated package.json | no changes
» ios: ios.usesIcloudStorage: Install expo-document-picker to enable the ios.usesIcloudStorage feature
» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
⠋ Running prebuild************ scheme undefined
✖ Prebuild failed
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
    at correctForPath (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/xcode/lib/pbxProject.js:1682:38)
    at correctForResourcesPath (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/xcode/lib/pbxProject.js:1672:12)
    at pbxProject.addResourceFile (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/xcode/lib/pbxProject.js:258:9)
    at /Users/joshuamohrer/Coding/waveapp-clone/node_modules/expo-config-plugin-ios-share-extension/build/withShareExtensionXcodeTarget.js:37:20
    at async action (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/expo-config-plugin-ios-share-extension/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:23)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/expo-config-plugin-ios-share-extension/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
    at async interceptingMod (/Users/joshuamohrer/Coding/waveapp-clone/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)

**Comment by timedtext** [comment]
This is a known issue, please check [here](https://github.com/timedtext/expo-config-plugin-ios-share-extension#package-version-incompatibility).
